### PR TITLE
Issue 155 y input validity

### LINKED ISSUE #155: BUG FIX: Dynamic table input of Y unknown in API when running prediction
For fields in the dynamic table that are one-hot encoded to be "Y" or "Not Declared", a value of "Y" will raise a non-critical error in the API. The value for that column is set to 0 by default.

To reproduce:
- Submit a CSV or student form to predict
- On the dynamic table page, expand a random student
- In the "Athlete" field, change the answer to "Y" and save change
- In the API terminal, a message should be sent to the gist of "Unknown value in column [7], setting value to 0"

### PR DESCRIPTION
**Pull request by jVnels**
Since we had a step to set Y or N values to 1 or 0, that caused problems for the "Athlete" and "Raley College Tag Exists" fields across the board since they have values of "Y" or "Not Declared", causing value mismatches. To simplify things, those fields got changed to either Y or N.

Additionally, I removed a nearly exactly duplicate API endpoint and fixed the format for multiple files, hence the large number of line changes...

Closes #155

### CODE REVIEW

File: react/src/pages/StudentForm.tsx [hunk 1]
```diff
@@ -188,7 +188,7 @@ const StudentForm: React.FC = () => {
             const formDataToSend = new FormData();
             formDataToSend.append('file', csvBlob, fileName);
 
-            const response = await fetch('/api/upload_form', {
+            const response = await fetch('/api/upload_data', {
                 method: 'POST',
                 body: formDataToSend,
             });
```
Comment (simon-dunk) [inline react/src/pages/StudentForm.tsx:194]: Not sure what the issue is, but I get this error when trying to submit a form. 

image

File: react/src/pages/InformUser.tsx [hunk 2]
```diff
@@ -3,6 +3,47 @@ import { useLocation, Link } from 'react-router-dom';
 import '../css/InformUser.css';
 import { FaCheck, FaTimes, FaPencilAlt } from "react-icons/fa";
 import { Tooltip } from 'react-tooltip';
+import Papa from "papaparse";
```
Comment (simon-dunk) [inline react/src/pages/InformUser.tsx:6]: When a value in the table is getting edited, is the prediction being re-calculated through the model. Or is it just visual editing, and not getting dynamic predictions?

**Review by simon-dunk — CHANGES_REQUESTED** [review]

File: react/src/pages/StudentForm.tsx (hunk 1 above)
Comment (jVnels) [reply react/src/pages/StudentForm.tsx:194]: Fixed

**Review by simon-dunk — APPROVED** [review]
